### ISSUE TITLE
Timer integration for test.html

### ISSUE THREAD

**Issue by AigarsS** [Art1985ss/AuthDemo#11]
Jegor already provided some insight in timer functionality, needs to be integrated with test.html, so that:
timer starts for each user individually
user sees timer while taking test
when time ends, answered questions are submitted, further action from user is prevented

**Comment by rabestro** [comment]
# Countdown Timer

The timer can act as countdown timer if the countdown parameters is passed with a truly value to the start method. The minimum target value of the countdown timer is 0. 

## HTML
```html
<div id="countdownExample">
    <div class="values"></div>
</div>
```

## JavaScript

```javascript
var timer = new Timer();
timer.start({countdown: true, startValues: {seconds: 30}});
$('#countdownExample .values').html(timer.getTimeValues().toString());
timer.addEventListener('secondsUpdated', function (e) {
    $('#countdownExample .values').html(timer.getTimeValues().toString());
});
timer.addEventListener('targetAchieved', function (e) {
    $('#countdownExample .values').html('KABOOM!!');
});
```
